name: Docker Image CI

on:
  push:
    branches:
    - release/*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.2.0
